# Generated by Django 4.2 on 2023-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avater',
            new_name='avatar',
        ),
    ]
